name: pub2port
description: A MacPorts (partial) portfile generator for Dart projects
version: 0.0.1
repository: https://github.com/amake/pub2port

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  pubspec_lock: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  pub2port:
